---
- hosts: all
  become: true
  become_user: root
  vars:
      firewall:
          - { port: '7070/tcp', state: 'disabled' }
          - { port: '80/tcp', state: 'disabled' }
          - { port: '22/tcp', state: 'enabled' }
      SELinux_restore_dirs:
        - /
  post_tasks:
      - name: Enable SELinux
        selinux:
          policy: targeted
          state: enforcing
      - name: Reboot the machine
        shell: sleep 2 && shutdown -r now
        async: 1
        poll: 0
      - name: Wait for machine to come back
        wait_for:
          port: 22
          host: "{{ ansible_default_ipv4.address }}"
          delay: 5
          timeout: 300
        delegate_to: localhost
        become: false
      - name: Gather new facts
        setup:
      - debug:
          msg: "SELinux status = {{ ansible_selinux.status }}"
  tasks:
      - name: Install Apache webserver
        package:
            name: httpd
            state: absent
      - name: Create custom path for Document Root
        file:
            path: /var/www_new/
            state: absent
      - name: Copy custom config files
        file:
            path: /etc/httpd/conf.d/custom_path.conf
            state: absent
      - name: Move index page for default path
        file:
            path: /var/www/html/index.html
            state: absent
      - name: Move index page for custom path
        file:
            path: /var/www_new/html/index.html
            state: absent
  roles:
      - linux-system-roles.firewall
      - linux-system-roles.selinux
