---
- set_fact:
    myhostname: "{{ ansible_fqdn }}"
  delegate_to: webservers

- name: Conditionally use inventory_hostname for myhostname if this is an EC2 instance
  set_fact:
    myhostname: "{{ inventory_hostname }}"
  when: ansible_product_version | regex_search('amazon')

- name: copy our wordpress template sql dumps
  template:
    src: templates/wordpress.sql
    dest: /tmp/wordpress.sql
    owner: root
    group: root
    mode: 0644

- name: "Import database for {{ wpdbname }}"
  mysql_db:
    name: "{{ wpdbname }}"
    state: import
    target: /tmp/wordpress.sql

- name: "Create the user {{ wpdbuser }} for {{ wpdbname }}.*:ALL"
  mysql_user:
    host: '%'
    name: "{{ wpdbuser }}"
    password: "{{ wpdbpass }}"
    priv: "{{ wpdbname }}.*:CREATE,DROP,DELETE,INSERT,SELECT,UPDATE"
    update_password: always
    state: present

- name: "Remove wordpress.sql template database if it still exists"
  file:
    path: /tmp/wordpress.sql
    state: absent
  changed_when: no
