---
- hosts: all
  vars:
    sat_hostname: "{{ sat_hostname }}"
    tools_channel: "{{ tools_channel }}"
    activation_key: "{{ activation_key }}"
    org_id: "{{ org_id }}"
  tasks:
  - name: Make sure DNS is set up correctly
    nmcli: conn_name=eth0 dns4="192.168.0.1" state=present
  - name: Install Satellite Certificate and Subscription Manager Configuration RPM
    command: "/usr/bin/yum -y localinstall http://{{ sat_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm"
  - name: Register with Satellite
    redhat_subscription:
      state: present
      activationkey: "{{ activation_key }}"
      org_id: "{{ org_id }}"
      autosubscribe: yes
      force_register: true
  - name: Enable Satellite Tools Repository
    command: "/usr/bin/subscription-manager repos --enable {{ tools_channel }}"
  - name: Install Katello Agent
    yum: pkg=katello-agent state=latest
  - name: Enable Katello Agent
    service: name=goferd enabled=yes
  - name: Start Katello Agent
    service: name=goferd state=started
  - name: Install Red Hat Access Insights Agent
    yum: pkg=redhat-access-insights state=present
  - name: Configure Red Hat Access Insights
    command: "redhat-access-insights --register"
