---
- name: Use Satellite API to delete content host
  hosts: all
  connection: local
  gather_facts: no
  vars:
    satelliteurl: "{{ sat_hostname }}"
    client: "{{ ansible_play_hosts[0] }}"
    user: "{{ sat_user }}"
    password: "{{ sat_password }}"
  tasks:
    - name: Get content host ID
      uri:
        url: "https://{{ satelliteurl }}/api/v2/hosts/{{ client }}"
        method: GET
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
      register: restdata
      ignore_errors: yes
    - name: delete satellite content host
      uri:
        url: "https://{{ satelliteurl }}/api/v2/hosts/{{ restdata.json.id }}"
        method: DELETE
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
      when: restdata|succeeded
- name: Clean up subscription manager
  hosts: all
  tasks:
    - name: Unregister Subscription Manager
      command: "subscription-manager unregister"
      ignore_errors: yes
    - name: Clean Subscription Manager
      command: "subscription-manager clean"
      ignore_errors: yes
