---
- name: Use Satellite API to delete content host
  hosts: all
  connection: local
  gather_facts: no
  vars:
    satelliteurl: "{{ sat_hostname }}"
    client: "{{ ansible_play_hosts[0] }}"
    user: "{{ sat_user }}"
    password: "{{ sat_password }}"

  tasks:
    - name: Get content host ID
      uri:
        url: "https://{{ satelliteurl }}/api/v2/hosts/{{ client }}"
        method: GET
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
      register: restdata
      ignore_errors: yes
    - name: delete satellite content host
      uri:
        url: "https://{{ satelliteurl }}/api/v2/hosts/{{ restdata.json.id }}"
        method: DELETE
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
      when: restdata|succeeded
    - name: revoke puppet certificate (if any)
      uri:
        url: "https://{{ satelliteurl }}/puppet-ca/v1/certificate_status/{{ client }}?environment=KT_Default_Organization_Library_rhel7_soe_with_puppet_4"
        method: PUT
        body: >
          { "desired_state": "revoked" }
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
      when: restdata|succeeded
      register: revoked
    - name: delete satellite puppet certificate
      uri:
        url: "https://{{ satelliteurl }}//puppet-ca/v1/certificate_status/{{ client }}?environment=KT_Default_Organization_Library_rhel7_soe_with_puppet_4"
        method: DELETE
        user: "{{ user }}"
        password: "{{ password }}"
        force_basic_auth: yes
        validate_certs: no
      when: revoked|succeeded
