---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - katello-agent
    - ansible
    - scap-security-guide

- name: Run SCAP remediation
  shell: "ansible-playbook -i localhost, -c local /usr/share/scap-security-guide/ansible/{{ scap_profile_name }}.yml"
  register: scap_output
  when: scap_profile_name is definedVault713


- name: Log scap_output
  debug:
    var: scap_output
  when: verbose and scap_output is defined

# Add your own plays here
