---
- name: Run SCAP remediation
  shell: "ansible-playbook /usr/share/scap-security-guide/ansible/{{ scap_profile_name }}"
  register: scap_output
  when: scap_profile_name is defined
  
- name: Log scap_output
  debug:
    var: scap_output

# Add your own plays here
