---
- name: Regiser with Satellite
  shell: "{{ item }}"
  register: sat_register_output
  with_items:
    - rpm -Uvh http://sat6.summit.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    - subscription-manager register --org=Default_Organization --activationkey=rhel7beta
    - subscription-manager repos --enable rhel-7-server-satellite-tools-6.2-rpms --enable rhel-7-server-extras-beta-rpms

- name: Log sat_register_output
  debug:
    var: sat_register_output
  when: verbose and sat_register_output is defined

- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - katello-agent
    - ansible
    - scap-security-guide

- name: Insert ignore_errors in playbooks
  shell: >
    for yml in /usr/share/scap-security-guide/ansible/*.yml; do sed -i "/^    - name/a\      ignore_errors: true" $yml; done
  register: modify_playbooks_out

- name: Log modify_playbooks_out
  debug:
    var: modify_playbooks_out
  when: modify_playbooks_out is defined

- name: Run SCAP remediation playbook
  shell: "ansible-playbook -i localhost, -c local /usr/share/scap-security-guide/ansible/{{ scap_profile_name }}.yml"
  register: scap_output
  ignore_errors: true
  when: scap_profile_name is defined

- name: Log scap_output
  debug:
    var: scap_output
  when: verbose and scap_output is defined

# Add your own plays here
