---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - http://sat6.summit.example.com/pub/katello-ca-consumer-latest.noarch.rpm
    - katello-agent
    - ansible
    - scap-security-guide

- name: Regiser with Satellite
  shell: "{{ item }}"
  register: sat_register_output
  with_items:
    - subscription-manager register --org=Default_Organization --activationkey=rhel7beta
    - subscription-manager repos --enable rhel-7-server-satellite-tools-6.2-rpms --enable rhel-7-server-extras-beta-rpms

- name: Log sat_register_output
  debug:
    var: sat_register_output
  when: verbose and sat_register_output is defined

- name: Run SCAP remediation playbook
  shell: "ansible-playbook -i localhost, -c local /usr/share/scap-security-guide/ansible/{{ scap_profile_name }}.yml"
  register: scap_output
  when: scap_profile_name is defined

- name: Log scap_output
  debug:
    var: scap_output
  when: verbose and scap_output is defined

# Add your own plays here
