---
- name: Configure puppet client
  command: "puppet agent -t"
  ignore_errors: true
  register: config_puppet_output

- name: Log config_puppet_output
  debug:
    var: config_puppet_output
  when: verbose

- name: Executing foreman_scap_client
  shell: foreman_scap_client '{{ policy_id }}'
  register: command_result
  failed_when: command_result.rc != 0

- name: Log command_result
  debug:
    var: command_result
  when: verbose
