# OPTIONAL exploits pieces for security demos
---
- name: Copy our exploits catsploit-tools
  template:
    src: "templates/{{ item.name }}"
    dest: "{{ item.destdir }}/{{ item.name }}"
    mode: "{{ item.chmod }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
  with_items:
    - { name: "db_open_public_root.sh", destdir: "/tmp", chmod: "0755", user: "root", group: "wheel" }
    - { name: "db_open_public_root.sql", destdir: "/tmp", chmod: "0644", user: "root", group: "wheel" }
    - { name: "cat_meme_takeover.sh", destdir: "/tmp", chmod: "0755", user: "root", group: "wheel" }
    - { name: "cat_meme_takeover.sql", destdir: "/tmp", chmod: "0644", user: "root", group: "wheel" }

