---
- include: install/db-main.yml
  when: my_purpose == 'db'

- include: install/web-main.yml
  when: my_purpose == 'web'

- include: catsploit.yml
  when: inventory_hostname = 'lampweb'
  when: my_purpose == 'web'

- include: catsploit-tools.yml
  when: my_purpose == 'workstation'


