---
- hosts: "{{ HOSTS }}"
  vars:
    ssh_banner: yes
    sftp_enable: no

  roles:
  - motd-splash
  - hardening
  - dev-sec.ssh-hardening

  tasks:
  - name: Link SSH Banner
    file:
      path: /etc/ssh/banner.txt
      src: /etc/motd
      state: link

  - name: set sftp subsystem
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Subsystem sftp'
      line: Subsystem sftp  /usr/libexec/openssh/sftp-server
    notify: restart sshd      