---
- name: Install SELinux tools
  package:
    name:
      - libselinux-utils
      - libselinux-python
    state: present

- name: Install SELinux tool semanage on Red Hat Enterprise Linux 6/7
  package:
    name:
      - policycoreutils-python
    state: present
  when: ansible_distribution_major_version == "7" or ansible_distribution_major_version == "6" and ( ansible_distribution == "CentOS" or ansible_distribution == "RedHat" )

- name: Install SELinux tool semanage on Fedora or Red Hat Enterprise Linux 8
  package:
    name:
      - policycoreutils-python-utils
      - policycoreutils-python3
    state: present
  when: ansible_distribution == "Fedora" or ( ansible_distribution_major_version > "7" and ( ansible_distribution == "CentOS" or ansible_distribution == "RedHat" ))

- name: Set permanent SELinux mode
  selinux: policy={{ SELinux_type }} state={{ SELinux_mode }}
  when: SELinux_mode is defined

- name: Set running SELinux mode
  command: /usr/sbin/setenforce {{ SELinux_mode }}
  when: SELinux_mode is defined and SELinux_change_running is defined

- name: Drop all local modifications
  shell: echo -e -n "{{drop_local_modifications}}" | /usr/sbin/semanage -i -

- name: Reload SELinux policy
  command: semodule -R
  when: ansible_selinux.status != "disabled"

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('no') }}"
  with_items: " {{ SELinux_booleans | default([]) }}"

- name: Set SELinux file contexts
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    ftype:  "{{ item.ftype | default('a') }}"
    state:  'present'
    # FIXME: selevel, seuser
  with_items: "{{ SELinux_file_contexts | default([]) }}"

- name: Restore SELinux labels on filesystem tree
  command: /sbin/restorecon -R {{ item }}
  with_items: "{{ SELinux_restore_dirs | default([]) }}"

- name: Set an SELinux label on a port
  seport:
    ports: "{{ item.ports }}"
    proto: "{{ item.proto | default('tcp') }}"
    setype: "{{ item.setype }}"
    state: "{{ item.state | default(present) }}"
  with_items: "{{ SELinux_ports | default([]) }}"

- name: Set linux user to SELinux user mapping
  selogin:
    login: "{{ item.login }}"
    seuser: "{{ item.seuser }}"
    serange: "{{ item.serange | default('s0') }}"
    state: "{{ item.state | default(present) }}"
    reload: "{{ item.reload | default(False) }}"
  with_items: "{{ SELinux_logins | default([]) }}"
