---
- name: Lock down the accounts
  hosts: all

  vars:
    - dbhostname: "{{ hostvars['lampdb']['ansible_facts']['eth0']['ipv4']['address'] }}"
    - webhostname: "{{ hostvars['lampweb']['ansible_facts']['eth0']['ipv4']['address'] }}"

  tasks:

  - name: lock down accounts with blank password and world access
    mysql_user:
      name: root
      password: ''
      host: '%'
      state: absent

