---
- name: "Checking to see if mariadb is installed prior to us installing it"
  stat:
    path: "/usr/lib/systemd/system/mariadb.service"
  register: wassvcmaria

- name: Software packages are present
  yum:
    name:
      - unzip
      - MySQL-python
      - policycoreutils-python
      - mariadb
      - mariadb-server
    state: latest
