---
- pamd:
    name: "{{ item }}"
    type: auth
    control: required
    module_path: pam_faillock.so
    module_arguments: "preauth silent audit deny={{ pass_max_attempts}} unlock_time={{ pass_unlock_time }}"
  loop:
    - system-auth
    - password-auth
 
- pamd:
    name: "{{ item }}"
    type: auth
    control: [default=die]
    module_path: pam_faillock.so
    module_arguments: "authfail audit deny={{ pass_max_attempts}} unlock_time={{ pass_unlock_time }}"
  loop:
    - system-auth
    - password-auth

- pamd:
    name: "{{ item }}"
    type: account
    control: required
    module_path: pam_faillock.so
  loop:
    - system-auth
    - password-auth