---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Enable Ansible repository
    yum_repository:
      name: ansible-2.9-for-rhel-8-x86_64-rpms
      file: redhat # To use the same file as the subscription-manager
      description: "Red Hat Ansible Engine 2.8 for RHEL 8 x86_64 (RPMs)"
      baseurl: https://cdn.redhat.com/content/dist/layered/rhel8/x86_64/ansible/2.8/os
      gpgcheck: no
    when: ansible_distribution == 'RedHat'  # i.e. RHEL, not Fedora

  - name: Ensure SCAP Security Guide dependencies are installed
    package:
      name:
      - git
      - make
      - cmake
      - openscap-utils
      - openscap-scanner
      - scap-workbench
      - wget  # needed for the NIST test suite for SSG
      - ansible  # needed for Ansible validation
      - gedit
      state: installed

  - name: Ensure SCAP Security Guide dependencies are installed (RHEL7)
    package:
      name:
      - python-jinja2  # needed for the new SSG yaml/jinja2 port
      - PyYAML
      - python-pip
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "7"

  - name: Ensure SCAP Security Guide Tests dependencies are installed (RHEL7)
    pip:
      name:
      - pytest
      - docker
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "7"

  - name: Ensure SCAP Security Guide dependencies are installed (RHEL8, Fedora)
    package:
      name:
      - python3-jinja2
      - python3-pytest  # needed for unit tests + coverage
      - python3-PyYAML
      state: installed
    when: (ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "8") or ansible_distribution == 'Fedora'

  - name: Ensure SCAP Security Guide Tests dependencies are installed (RHEL8, Fedora)
    package:
      name:
      - podman
    when: (ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "8") or ansible_distribution == 'Fedora'

  - name: Ensure that lab-user exists
    user:
      name: lab-user
      password: $6$slKF3uSy7AUr0NS3$jS23cqtNIGmj2reBpyvc0O7pXDl10tUYNDZELRcVGwMAAWeNajOQMHStLr3mYemOFv7P5vPmrsKCfUWDRMyZg1  # r3dh4t1!
      update_password: on_create

  # Taken from https://stackoverflow.com/questions/33359404/ansible-best-practice-for-maintaining-list-of-sudoers
  - name: Ensure that lab-user can do passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^lab-user'
      line: 'lab-user ALL=(ALL)       NOPASSWD: ALL'
      validate: visudo -cf %s
